# Generated by Django 5.1.2 on 2024-11-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPageAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Advertisement Name')),
                ('adv_description', models.TextField(blank=True, null=True, verbose_name='Advertisement Description')),
                ('adv_link', models.URLField(blank=True, null=True, verbose_name='Advertisement Link')),
                ('adv_image', models.ImageField(upload_to='ads/', verbose_name='Advertisement Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
    ]
