# Generated by Django 5.1.2 on 2024-11-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_indexpageads_options_indexpageads_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembercard',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='team_pictures/', verbose_name='About Image'),
        ),
        migrations.AddField(
            model_name='teammembercard',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='team_pictures/', verbose_name='Featured Image'),
        ),
    ]
