# Generated by Django 5.1.2 on 2024-12-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_shippingaddress_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='payment_method',
            field=models.CharField(choices=[('pay_on_delivery', 'Pay on Delivery'), ('bank_payment', 'Bank Payment')], default='pay_on_delivery', max_length=20),
        ),
    ]
