# Generated by Django 5.1.2 on 2024-11-22 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepictures',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='services.services', verbose_name='Pictures'),
        ),
        migrations.AlterField(
            model_name='servicepricing',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='services.services', verbose_name='Pricing'),
        ),
    ]
