# Generated by Django 5.1.2 on 2024-11-23 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_servicepictures_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepictures',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='services.services', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='servicepricing',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='services.services', verbose_name='Service'),
        ),
    ]
