# Generated by Django 5.1.2 on 2024-11-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferred_name_nickname',
            field=models.CharField(default='Anonymous', help_text='Please enter preferred name/nickname for personalized communication', max_length=150),
        ),
    ]
