# Generated by Django 5.1.2 on 2024-11-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMemberCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='team_pictures/', verbose_name='Profile Picture')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Card Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Card Description')),
                ('role', models.CharField(blank=True, max_length=100, null=True, verbose_name='Role')),
                ('specialities', models.TextField(blank=True, null=True, verbose_name='Specialties')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('appearance_order', models.PositiveIntegerField(default=2, verbose_name='Ordering')),
            ],
            options={
                'verbose_name': 'Team Member Card',
                'verbose_name_plural': 'Team Member Cards',
                'ordering': ['appearance_order', '-updated_at'],
            },
        ),
    ]
