# Generated by Django 5.1.2 on 2024-11-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontent',
            name='left_image',
            field=models.ImageField(help_text='For optimal display, upload an image with dimensions 600x400 pixels or an aspect ratio of 3:2 ', upload_to='blog_images/'),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='main_image',
            field=models.ImageField(help_text='For optimal display, upload an image with dimensions 1280x720 pixels or an aspect ratio of 16:9 ', upload_to='blog_images/'),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='right_image',
            field=models.ImageField(help_text='For optimal display, upload an image with dimensions 558x391 pixels or an aspect ratio of 3:2 ', upload_to='blog_images/'),
        ),
    ]
