# Generated by Django 5.1.2 on 2024-11-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='email',
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.TextField(max_length=200),
        ),
    ]
